name: Build standalone kernel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Build setup
        run: |
          ./build.sh envcheck
          echo "date=$(date +'%Y%m%d-%H%M')" >> "$GITHUB_ENV"

      - name: Download source
        run: ./build.sh getsource
    
      - name: Download prebuilts & scripts
        run: ./build.sh gettools

      - name: Build kernel
        run: ./build.sh startbuild

      - name: Post-build
        run: |
          ./build.sh finalize
          echo "sfx=$(cat VERSION.txt)" >> "$GITHUB_ENV"

      - name: Upload updater zip
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3_veux-${{ env.sfx }}_${{ env.date }}
          path: AnyKernel3/**
          if-no-files-found: error
